/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void button_init(void);
uint32_t g_button_pressed;
uint32_t g_button_press_count = 0;


uint32_t volatile *pEXTI_PR		= (uint32_t*) (0x40013C00 +  0x14);
uint32_t volatile *pAHB1ENR		= (uint32_t*) (0x40023800 +  0x30);
uint32_t volatile *pAPB2ENR		= (uint32_t*) (0x40023800 +  0x44);
uint32_t volatile *pGPIOA_MODER	= (uint32_t*) (0x40020000 +  0x00);
uint32_t volatile *pGPIOA_IDR	= (uint32_t*) (0x40020000 +  0x10);
uint32_t volatile *pEXTI_IMR	= (uint32_t*) (0x40013C00 +  0x00);
uint32_t volatile *pEXTI_RTSR	= (uint32_t*) (0x40013C00 +  0x08);
uint32_t volatile *pNVICIRQEn	= (uint32_t*)  0xE000E100;




int main(void)
{

	button_init();
    /* Loop forever */
	while(1)
	{

		//Disable interrupt
		*pEXTI_IMR &= ~(1 << 0);

		if (g_button_pressed)
		{
			//some delay until debouncing gets over
			for(uint32_t volatile i=0; i < 100000/2; i++);
			g_button_press_count++;
			printf("Button is pressed : %lu\n",g_button_press_count);
			g_button_pressed = 0;
		}
	//Enable Interrupt
		*pEXTI_IMR |= (1 << 0);
	}
}

void button_init(void)
{
	/* GPIOA Clock Enable */
	*pAHB1ENR |= (1 << 0);
	/* syscfg clock enable */
	*pAPB2ENR |= (1 << 14);
	/* Edge detection configuration */
	*pEXTI_RTSR |= (1 << 0);
	/*EXTI interrupt enable */
	*pEXTI_IMR |= (1 << 0);
	/*NVIC irq enable */
	*pNVICIRQEn |= (1 << 6);

	//Check for button status
	g_button_pressed = (uint32_t)pGPIOA_IDR;
}

/* This is button Interrupt Handler */

void EXTI0_IRQHandler(void)
{
	printf("Interrupt Occured\n");
	//Make this Flag set, if button pressed
	g_button_pressed = 1;

	//CLearing of EXTI interrupt pending bit
	*pEXTI_PR |= (1 << 0);

}
